sudo: false
language: go
services:
  - docker
go:
  - "1.11.x"
git:
  depth: 1

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/goph/licensei/cmd/licensei
install:
  - dep ensure
script:
  - make check
notifications:
  email: false